### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by t-b** [byte-physics/igor-code-browser#38]
- [x] Add help entries for panel, Capitalize all names
- [x] Adapt copyright year in each file, refer to `LICENSE` in each file
- [x] Remove authors from each file
- [x] Adapt year in LICENSE
- [x] Remove ugly whitespace as highlighted in vim
- [x] Raise version in ipf files
- [x] Write human readable changelog
- [x] tag and push tag
- [x] add new release on github
- [ ] release on igor-exchange

**Comment by t-b** [comment]
@ukos-git Could you take care of these issues? I would only need to do the last one.

I'm also thinking about ditching releases alltogether and just offering `head` as latest version. Thought?

**Comment by ukos-git** [comment]
Release Notes:

changes since 2016/04/10 (Release Version 1.2)

Features:

* Add <ALL> for Namespace and Procedures to select all items in the current listbox.
* Add option to filter procedure files according to certain patterns like `CodeBrowser*`.
* save last selected procedure, namespace, search, filter and listbox item in package preferences on codebrowser exit.
* Add menu items to the list of elements.
* Display the comment lines above the function definition as html formatted help text (QT, requires IP8)
* Make CodeBrowser a floating panel
* Performance enhancement by calling ProcedureText() only once.
* Switch to rolling releases under BSD 3-clause on https://github.com/byte-physics/igor-code-browser
* Support for structure name parsing in functions with only one structure as input like Window Hooks with WMWinHookStruct.
* Partly switch to doxygen comments.
* Internal changes to the BeforeQuitHook.
* Internal changes to the global variable management and package folder cleanup.

Bugfixes:

* Fix a bug where an empty function list was marked valid in "not compiled" state.
* Fix variable deletion on Igor Exit.
* Move initialized state from userdata to global variable because BeforeQuitHook is behaving strangly in some occasions.
* Allow to jump to the selected procedure file in uncompiled state.
* Fall back to last compiled state for display when procedures are not compiled.
* Fix and enhance constant parsing.
* Searching in empty procedures lead to a crash.
* Fix parsing of nested Independent Modules.

**Comment by t-b** [comment]
@ukos-git Done, see https://www.wavemetrics.com/project/codebrowser.
