### ISSUE TITLE
open procedure file if procedures are not compiled and a user clicked into the listbox

### ISSUE THREAD

**Issue by t-b** [byte-physics/igor-code-browser#5]

**Comment by ukos-git** [comment]
This is also related to not showing Functions while in an uncompiled state.

since it is [only the functions part](https://github.com/ukos-git/igor-code-browser/blob/a40a2a9c061647b8701c88f67d0a076dd6b13e68/procedures/CodeBrowser.ipf#L297) that is using `FunctionList` while all others use regex, I would recommend, also to change the search to regex.

**Comment by ukos-git** [comment]
I think it would be hard to recreate all function definitions with inline variable definitions etc but for the simple functions there should be a work-around when in un-compiled state. Therefore I suggest two Wrappers for `FunctionList` and `FunctionInfo` that work with regex in un-compiled state.

It would be a fall-back for that "special" situation.

**Comment by t-b** [comment]
@ukos-git Hmm is that really a problem in practice? If we have parsed it once we can rely on the contents no matter if the procedures are compiled or not.

**Comment by ukos-git** [comment]
Spaces were copy-pasted from https://www.wavemetrics.com/code-snippet/datafolderexists-data-folder-references

like a python-copy/paste problem :-)
